create table "public"."handpicked" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "book_id" text,
    "cover" text,
    "order" numeric
);


alter table "public"."handpicked" enable row level security;

CREATE UNIQUE INDEX handpicked_pkey ON public.handpicked USING btree (id);


alter table "public"."handpicked" add constraint "handpicked_pkey" PRIMARY KEY using index "handpicked_pkey";


grant delete on table "public"."handpicked" to "anon";

grant insert on table "public"."handpicked" to "anon";

grant references on table "public"."handpicked" to "anon";

grant select on table "public"."handpicked" to "anon";

grant trigger on table "public"."handpicked" to "anon";

grant truncate on table "public"."handpicked" to "anon";

grant update on table "public"."handpicked" to "anon";

grant delete on table "public"."handpicked" to "authenticated";

grant insert on table "public"."handpicked" to "authenticated";

grant references on table "public"."handpicked" to "authenticated";

grant select on table "public"."handpicked" to "authenticated";

grant trigger on table "public"."handpicked" to "authenticated";

grant truncate on table "public"."handpicked" to "authenticated";

grant update on table "public"."handpicked" to "authenticated";

grant delete on table "public"."handpicked" to "service_role";

grant insert on table "public"."handpicked" to "service_role";

grant references on table "public"."handpicked" to "service_role";

grant select on table "public"."handpicked" to "service_role";

grant trigger on table "public"."handpicked" to "service_role";

grant truncate on table "public"."handpicked" to "service_role";

grant update on table "public"."handpicked" to "service_role";

create policy "Enable read access for all users"
on "public"."handpicked"
as permissive
for select
to authenticated
using (true);



