create table "public"."daily_dose" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "language" text,
    "book_id" text
);


alter table "public"."daily_dose" enable row level security;

CREATE UNIQUE INDEX daily_dosese_pkey ON public.daily_dose USING btree (id);


alter table "public"."daily_dose" add constraint "daily_dosese_pkey" PRIMARY KEY using index "daily_dosese_pkey";


grant delete on table "public"."daily_dose" to "anon";

grant insert on table "public"."daily_dose" to "anon";

grant references on table "public"."daily_dose" to "anon";

grant select on table "public"."daily_dose" to "anon";

grant trigger on table "public"."daily_dose" to "anon";

grant truncate on table "public"."daily_dose" to "anon";

grant update on table "public"."daily_dose" to "anon";

grant delete on table "public"."daily_dose" to "authenticated";

grant insert on table "public"."daily_dose" to "authenticated";

grant references on table "public"."daily_dose" to "authenticated";

grant select on table "public"."daily_dose" to "authenticated";

grant trigger on table "public"."daily_dose" to "authenticated";

grant truncate on table "public"."daily_dose" to "authenticated";

grant update on table "public"."daily_dose" to "authenticated";

grant delete on table "public"."daily_dose" to "service_role";

grant insert on table "public"."daily_dose" to "service_role";

grant references on table "public"."daily_dose" to "service_role";

grant select on table "public"."daily_dose" to "service_role";

grant trigger on table "public"."daily_dose" to "service_role";

grant truncate on table "public"."daily_dose" to "service_role";

grant update on table "public"."daily_dose" to "service_role";


