create table "public"."prologue_audio" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "path" text,
    "language" text
);


CREATE INDEX idx_library_books_audiobook ON public.library_books USING btree (id) WHERE (file_type = 'audiobook'::text);

CREATE INDEX idx_library_books_book_id ON public.library_books USING btree (book_id);

CREATE INDEX idx_library_books_collection_name ON public.library_books USING btree (collection_name);

CREATE INDEX idx_library_books_created_at ON public.library_books USING btree (created_at);

CREATE INDEX idx_library_books_ebook ON public.library_books USING btree (id) WHERE (file_type = 'ebook'::text);

CREATE INDEX idx_library_books_metadata ON public.library_books USING gin (metadata);

CREATE UNIQUE INDEX prologue_audio_pkey ON public.prologue_audio USING btree (id);


alter table "public"."prologue_audio" add constraint "prologue_audio_pkey" PRIMARY KEY using index "prologue_audio_pkey";


grant delete on table "public"."prologue_audio" to "anon";

grant insert on table "public"."prologue_audio" to "anon";

grant references on table "public"."prologue_audio" to "anon";

grant select on table "public"."prologue_audio" to "anon";

grant trigger on table "public"."prologue_audio" to "anon";

grant truncate on table "public"."prologue_audio" to "anon";

grant update on table "public"."prologue_audio" to "anon";

grant delete on table "public"."prologue_audio" to "authenticated";

grant insert on table "public"."prologue_audio" to "authenticated";

grant references on table "public"."prologue_audio" to "authenticated";

grant select on table "public"."prologue_audio" to "authenticated";

grant trigger on table "public"."prologue_audio" to "authenticated";

grant truncate on table "public"."prologue_audio" to "authenticated";

grant update on table "public"."prologue_audio" to "authenticated";

grant delete on table "public"."prologue_audio" to "service_role";

grant insert on table "public"."prologue_audio" to "service_role";

grant references on table "public"."prologue_audio" to "service_role";

grant select on table "public"."prologue_audio" to "service_role";

grant trigger on table "public"."prologue_audio" to "service_role";

grant truncate on table "public"."prologue_audio" to "service_role";

grant update on table "public"."prologue_audio" to "service_role";


