create table "public"."authors_de" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "century" text,
    "ektype" text,
    "name" text,
    "image" text
);


alter table "public"."authors_de" enable row level security;

create table "public"."authors_en" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "century" text,
    "ektype" text,
    "name" text,
    "image" text
);


alter table "public"."authors_en" enable row level security;

CREATE UNIQUE INDEX authors_de_pkey ON public.authors_de USING btree (id);

CREATE UNIQUE INDEX authors_pkey ON public.authors_en USING btree (id);


alter table "public"."authors_de" add constraint "authors_de_pkey" PRIMARY KEY using index "authors_de_pkey";

alter table "public"."authors_en" add constraint "authors_pkey" PRIMARY KEY using index "authors_pkey";


grant delete on table "public"."authors_de" to "anon";

grant insert on table "public"."authors_de" to "anon";

grant references on table "public"."authors_de" to "anon";

grant select on table "public"."authors_de" to "anon";

grant trigger on table "public"."authors_de" to "anon";

grant truncate on table "public"."authors_de" to "anon";

grant update on table "public"."authors_de" to "anon";

grant delete on table "public"."authors_de" to "authenticated";

grant insert on table "public"."authors_de" to "authenticated";

grant references on table "public"."authors_de" to "authenticated";

grant select on table "public"."authors_de" to "authenticated";

grant trigger on table "public"."authors_de" to "authenticated";

grant truncate on table "public"."authors_de" to "authenticated";

grant update on table "public"."authors_de" to "authenticated";

grant delete on table "public"."authors_de" to "service_role";

grant insert on table "public"."authors_de" to "service_role";

grant references on table "public"."authors_de" to "service_role";

grant select on table "public"."authors_de" to "service_role";

grant trigger on table "public"."authors_de" to "service_role";

grant truncate on table "public"."authors_de" to "service_role";

grant update on table "public"."authors_de" to "service_role";

grant delete on table "public"."authors_en" to "anon";

grant insert on table "public"."authors_en" to "anon";

grant references on table "public"."authors_en" to "anon";

grant select on table "public"."authors_en" to "anon";

grant trigger on table "public"."authors_en" to "anon";

grant truncate on table "public"."authors_en" to "anon";

grant update on table "public"."authors_en" to "anon";

grant delete on table "public"."authors_en" to "authenticated";

grant insert on table "public"."authors_en" to "authenticated";

grant references on table "public"."authors_en" to "authenticated";

grant select on table "public"."authors_en" to "authenticated";

grant trigger on table "public"."authors_en" to "authenticated";

grant truncate on table "public"."authors_en" to "authenticated";

grant update on table "public"."authors_en" to "authenticated";

grant delete on table "public"."authors_en" to "service_role";

grant insert on table "public"."authors_en" to "service_role";

grant references on table "public"."authors_en" to "service_role";

grant select on table "public"."authors_en" to "service_role";

grant trigger on table "public"."authors_en" to "service_role";

grant truncate on table "public"."authors_en" to "service_role";

grant update on table "public"."authors_en" to "service_role";


