create table "public"."theosis_highlights_de" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "audio" text,
    "cover" text,
    "cover_mini" text,
    "name" text,
    "episode_number" numeric,
    "is_published" boolean default false
);


alter table "public"."theosis_highlights_de" enable row level security;

create table "public"."theosis_highlights_en" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "audio" text,
    "cover" text,
    "cover_mini" text,
    "name" text,
    "episode_number" numeric,
    "is_published" boolean default false
);


alter table "public"."theosis_highlights_en" enable row level security;

CREATE UNIQUE INDEX theosis_highlights_de_pkey ON public.theosis_highlights_de USING btree (id);

CREATE UNIQUE INDEX theosis_highlights_en_pkey ON public.theosis_highlights_en USING btree (id);


alter table "public"."theosis_highlights_de" add constraint "theosis_highlights_de_pkey" PRIMARY KEY using index "theosis_highlights_de_pkey";

alter table "public"."theosis_highlights_en" add constraint "theosis_highlights_en_pkey" PRIMARY KEY using index "theosis_highlights_en_pkey";


grant delete on table "public"."theosis_highlights_de" to "anon";

grant insert on table "public"."theosis_highlights_de" to "anon";

grant references on table "public"."theosis_highlights_de" to "anon";

grant select on table "public"."theosis_highlights_de" to "anon";

grant trigger on table "public"."theosis_highlights_de" to "anon";

grant truncate on table "public"."theosis_highlights_de" to "anon";

grant update on table "public"."theosis_highlights_de" to "anon";

grant delete on table "public"."theosis_highlights_de" to "authenticated";

grant insert on table "public"."theosis_highlights_de" to "authenticated";

grant references on table "public"."theosis_highlights_de" to "authenticated";

grant select on table "public"."theosis_highlights_de" to "authenticated";

grant trigger on table "public"."theosis_highlights_de" to "authenticated";

grant truncate on table "public"."theosis_highlights_de" to "authenticated";

grant update on table "public"."theosis_highlights_de" to "authenticated";

grant delete on table "public"."theosis_highlights_de" to "service_role";

grant insert on table "public"."theosis_highlights_de" to "service_role";

grant references on table "public"."theosis_highlights_de" to "service_role";

grant select on table "public"."theosis_highlights_de" to "service_role";

grant trigger on table "public"."theosis_highlights_de" to "service_role";

grant truncate on table "public"."theosis_highlights_de" to "service_role";

grant update on table "public"."theosis_highlights_de" to "service_role";

grant delete on table "public"."theosis_highlights_en" to "anon";

grant insert on table "public"."theosis_highlights_en" to "anon";

grant references on table "public"."theosis_highlights_en" to "anon";

grant select on table "public"."theosis_highlights_en" to "anon";

grant trigger on table "public"."theosis_highlights_en" to "anon";

grant truncate on table "public"."theosis_highlights_en" to "anon";

grant update on table "public"."theosis_highlights_en" to "anon";

grant delete on table "public"."theosis_highlights_en" to "authenticated";

grant insert on table "public"."theosis_highlights_en" to "authenticated";

grant references on table "public"."theosis_highlights_en" to "authenticated";

grant select on table "public"."theosis_highlights_en" to "authenticated";

grant trigger on table "public"."theosis_highlights_en" to "authenticated";

grant truncate on table "public"."theosis_highlights_en" to "authenticated";

grant update on table "public"."theosis_highlights_en" to "authenticated";

grant delete on table "public"."theosis_highlights_en" to "service_role";

grant insert on table "public"."theosis_highlights_en" to "service_role";

grant references on table "public"."theosis_highlights_en" to "service_role";

grant select on table "public"."theosis_highlights_en" to "service_role";

grant trigger on table "public"."theosis_highlights_en" to "service_role";

grant truncate on table "public"."theosis_highlights_en" to "service_role";

grant update on table "public"."theosis_highlights_en" to "service_role";


